#Este YAML solo define los nombres de cada junta en el robot y el ID que tienen. El nombre se puede cambiar a lo que se desee.
joint_1:
  ID: 1
  Return_Delay_Time: 0
joint_2:
  ID: 2
  Return_Delay_Time: 0
joint_3:
  ID: 3
  Return_Delay_Time: 0
joint_4:
  ID: 4
  Return_Delay_Time: 0
joint_5:
  ID: 5
  Return_Delay_Time: 0